TCI's data are set in the form
anthropedia/tci-online pull request #5
Opened 2017-04-27 21:49 UTC by Ydrasil

The data are correctly received in backend

2017-04-28 08:40 UTC, Ydrasil commented
@vinyll

2017-04-28 09:05 UTC, vinyll requested changes

2017-04-28 09:05 UTC, vinyll commented on app.py
> +        verify_token = Token.objects.get(key=token, usage_date=None)
`verify_token = ` is not used. Delete it.

2017-04-28 09:05 UTC, vinyll commented on templates/survey.html
> +  form.addEventListener('submit', event => {
Move this up below the other `form.addEventListener`

2017-04-28 10:09 UTC, vinyll commented on templates/survey.html
> +  function step(index) {
move this down next to `function end()`

2017-04-29 09:10 UTC, Ydrasil commented
@vinyll changes done

2017-04-29 09:31 UTC, vinyll requested changes

2017-04-29 09:31 UTC, vinyll commented on static/style.css
> +.incomplete button {
Is this still useful? There's nomore button in the HTML

2017-04-29 18:37 UTC, Ydrasil commented on static/style.css
> +.incomplete button {
I've changed that

2017-05-11 14:07 UTC, closed without merging